from datetime import UTC, datetime
from sqlite3 import Connection


CUSTOMERS = [
    {"id": 1, "name": "Maya Patel"},
    {"id": 2, "name": "Jordan Lee"},
]


def product_image(query: str) -> str:
    slug = query.lower().replace("&", "and").replace("%", "").replace(" ", "-")
    return f"/products/{slug}.svg"


PRODUCTS = [
    {
        "name": "Whole Milk",
        "category": "Dairy",
        "sample_price": 4.49,
        "package_size": "half gallon",
        "image_url": product_image("whole milk grocery"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 14,
        "guidance": "Check sell-by date and choose the furthest-dated carton.",
    },
    {
        "name": "2% Milk",
        "category": "Dairy",
        "sample_price": 4.29,
        "package_size": "half gallon",
        "image_url": product_image("reduced fat milk grocery"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 14,
        "guidance": "Check sell-by date and avoid cartons with dents or leaking caps.",
    },
    {
        "name": "Greek Yogurt",
        "category": "Dairy",
        "sample_price": 5.99,
        "package_size": "32 oz tub",
        "image_url": product_image("greek yogurt bowl"),
        "typical_shelf_life_days": 10,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Prefer sealed cups or tubs with no lid bulging.",
    },
    {
        "name": "Plain Yogurt",
        "category": "Dairy",
        "sample_price": 4.49,
        "package_size": "32 oz tub",
        "image_url": product_image("plain yogurt grocery"),
        "typical_shelf_life_days": 10,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Choose sealed tubs with the latest best-by date.",
    },
    {
        "name": "Butter",
        "category": "Dairy",
        "sample_price": 4.99,
        "package_size": "1 lb box",
        "image_url": product_image("butter dairy"),
        "typical_shelf_life_days": 30,
        "max_realistic_shelf_life_days": 90,
        "guidance": "Pick boxes from the back of the cooler with intact wrapping.",
    },
    {
        "name": "Cheddar Cheese",
        "category": "Dairy",
        "sample_price": 3.99,
        "package_size": "8 oz block",
        "image_url": product_image("cheddar cheese block"),
        "typical_shelf_life_days": 21,
        "max_realistic_shelf_life_days": 60,
        "guidance": "Avoid torn packaging and choose the latest date.",
    },
    {
        "name": "Mozzarella Cheese",
        "category": "Dairy",
        "sample_price": 4.49,
        "package_size": "8 oz shredded",
        "image_url": product_image("mozzarella cheese"),
        "typical_shelf_life_days": 14,
        "max_realistic_shelf_life_days": 45,
        "guidance": "Prefer sealed bags with no excess moisture or air loss.",
    },
    {
        "name": "Cottage Cheese",
        "category": "Dairy",
        "sample_price": 4.29,
        "package_size": "16 oz tub",
        "image_url": product_image("cottage cheese"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Choose a sealed tub with the latest use-by date.",
    },
    {
        "name": "Sour Cream",
        "category": "Dairy",
        "sample_price": 2.99,
        "package_size": "16 oz tub",
        "image_url": product_image("sour cream"),
        "typical_shelf_life_days": 10,
        "max_realistic_shelf_life_days": 30,
        "guidance": "Avoid cracked lids and select the latest date.",
    },
    {
        "name": "Heavy Cream",
        "category": "Dairy",
        "sample_price": 4.79,
        "package_size": "pint",
        "image_url": product_image("heavy cream carton"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Check for the furthest-dated carton and intact cap.",
    },
    {
        "name": "Eggs",
        "category": "Dairy",
        "sample_price": 3.89,
        "package_size": "dozen",
        "image_url": product_image("eggs carton grocery"),
        "typical_shelf_life_days": 21,
        "max_realistic_shelf_life_days": 35,
        "guidance": "Open carton and check for cracks before accepting.",
    },
    {
        "name": "Chicken Breast",
        "category": "Meat",
        "sample_price": 9.49,
        "package_size": "1.5 lb pack",
        "image_url": product_image("chicken breast grocery"),
        "typical_shelf_life_days": 2,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Choose packages with the latest use-by date and no leaking.",
    },
    {
        "name": "Chicken Thighs",
        "category": "Meat",
        "sample_price": 8.49,
        "package_size": "1.5 lb pack",
        "image_url": product_image("chicken thighs"),
        "typical_shelf_life_days": 2,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Select clean packaging with the latest use-by date.",
    },
    {
        "name": "Ground Chicken",
        "category": "Meat",
        "sample_price": 6.99,
        "package_size": "1 lb pack",
        "image_url": product_image("ground chicken"),
        "typical_shelf_life_days": 2,
        "max_realistic_shelf_life_days": 4,
        "guidance": "Choose tightly sealed packs with no excess liquid.",
    },
    {
        "name": "Ground Beef",
        "category": "Meat",
        "sample_price": 7.99,
        "package_size": "1 lb pack",
        "image_url": product_image("ground beef grocery"),
        "typical_shelf_life_days": 2,
        "max_realistic_shelf_life_days": 4,
        "guidance": "Prefer bright, sealed packages with the latest date.",
    },
    {
        "name": "Beef Steak",
        "category": "Meat",
        "sample_price": 12.99,
        "package_size": "1 lb pack",
        "image_url": product_image("beef steak"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Choose well-sealed cuts with minimal discoloration.",
    },
    {
        "name": "Lamb Chops",
        "category": "Meat",
        "sample_price": 14.99,
        "package_size": "1 lb pack",
        "image_url": product_image("lamb chops"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Pick the freshest-dated tray with secure wrapping.",
    },
    {
        "name": "Pork Chops",
        "category": "Meat",
        "sample_price": 8.99,
        "package_size": "1.25 lb pack",
        "image_url": product_image("pork chops"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Avoid torn film or liquid pooling in the package.",
    },
    {
        "name": "Turkey Breast",
        "category": "Meat",
        "sample_price": 10.99,
        "package_size": "1.5 lb pack",
        "image_url": product_image("turkey breast"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 6,
        "guidance": "Choose the latest date and intact packaging.",
    },
    {
        "name": "Sausage",
        "category": "Meat",
        "sample_price": 5.99,
        "package_size": "14 oz pack",
        "image_url": product_image("sausage grocery"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 14,
        "guidance": "Select sealed packs with no leaking or swelling.",
    },
    {
        "name": "Bacon",
        "category": "Meat",
        "sample_price": 6.49,
        "package_size": "12 oz pack",
        "image_url": product_image("bacon grocery"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Pick packs with the latest date and no broken seal.",
    },
    {
        "name": "Tomatoes",
        "category": "Vegetables",
        "sample_price": 2.49,
        "package_size": "per lb",
        "image_url": product_image("fresh tomatoes"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose firm tomatoes without bruising or splits.",
    },
    {
        "name": "Onions",
        "category": "Vegetables",
        "sample_price": 1.29,
        "package_size": "per lb",
        "image_url": product_image("yellow onions"),
        "typical_shelf_life_days": 14,
        "max_realistic_shelf_life_days": 30,
        "guidance": "Avoid soft spots and sprouting.",
    },
    {
        "name": "Potatoes",
        "category": "Vegetables",
        "sample_price": 3.99,
        "package_size": "5 lb bag",
        "image_url": product_image("potatoes grocery"),
        "typical_shelf_life_days": 14,
        "max_realistic_shelf_life_days": 30,
        "guidance": "Choose firm potatoes without green areas or sprouts.",
    },
    {
        "name": "Carrots",
        "category": "Vegetables",
        "sample_price": 2.49,
        "package_size": "2 lb bag",
        "image_url": product_image("carrots grocery"),
        "typical_shelf_life_days": 14,
        "max_realistic_shelf_life_days": 30,
        "guidance": "Pick firm carrots and avoid slimy bags.",
    },
    {
        "name": "Cucumbers",
        "category": "Vegetables",
        "sample_price": 0.99,
        "package_size": "each",
        "image_url": product_image("cucumbers grocery"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose firm cucumbers with no soft ends.",
    },
    {
        "name": "Bell Peppers",
        "category": "Vegetables",
        "sample_price": 1.49,
        "package_size": "each",
        "image_url": product_image("bell peppers"),
        "typical_shelf_life_days": 7,
        "max_realistic_shelf_life_days": 14,
        "guidance": "Choose glossy, firm peppers without wrinkles.",
    },
    {
        "name": "Broccoli",
        "category": "Vegetables",
        "sample_price": 2.29,
        "package_size": "bunch",
        "image_url": product_image("broccoli grocery"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Select tight green florets and firm stems.",
    },
    {
        "name": "Cauliflower",
        "category": "Vegetables",
        "sample_price": 3.49,
        "package_size": "head",
        "image_url": product_image("cauliflower grocery"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose compact heads without brown spotting.",
    },
    {
        "name": "Green Beans",
        "category": "Vegetables",
        "sample_price": 3.29,
        "package_size": "per lb",
        "image_url": product_image("green beans"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Pick crisp beans and avoid limp or spotted pieces.",
    },
    {
        "name": "Okra",
        "category": "Vegetables",
        "sample_price": 3.99,
        "package_size": "per lb",
        "image_url": product_image("okra vegetable"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Choose small, firm pods and avoid dark soft spots.",
    },
    {
        "name": "Spinach",
        "category": "Leafy Greens",
        "sample_price": 3.49,
        "package_size": "10 oz bag",
        "image_url": product_image("fresh spinach"),
        "typical_shelf_life_days": 4,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Avoid wilted leaves and excess moisture in the bag.",
    },
    {
        "name": "Chopped Spinach",
        "category": "Leafy Greens",
        "sample_price": 3.29,
        "package_size": "10 oz bag",
        "image_url": product_image("chopped spinach"),
        "typical_shelf_life_days": 4,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Choose bags with crisp greens and no pooled moisture.",
    },
    {
        "name": "Lettuce",
        "category": "Leafy Greens",
        "sample_price": 2.19,
        "package_size": "head",
        "image_url": product_image("lettuce head"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose firm heads without browning or soggy leaves.",
    },
    {
        "name": "Chopped Lettuce",
        "category": "Leafy Greens",
        "sample_price": 3.49,
        "package_size": "12 oz bag",
        "image_url": product_image("chopped lettuce"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Pick crisp bags with the latest date.",
    },
    {
        "name": "Romaine Lettuce",
        "category": "Leafy Greens",
        "sample_price": 3.99,
        "package_size": "3 count hearts",
        "image_url": product_image("romaine lettuce"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose crisp romaine with no rusty edges.",
    },
    {
        "name": "Spring Mix",
        "category": "Leafy Greens",
        "sample_price": 4.49,
        "package_size": "5 oz clamshell",
        "image_url": product_image("spring mix greens"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Avoid clamshells with wilted leaves or condensation.",
    },
    {
        "name": "Kale",
        "category": "Leafy Greens",
        "sample_price": 2.79,
        "package_size": "bunch",
        "image_url": product_image("kale bunch"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Select sturdy leaves without yellowing.",
    },
    {
        "name": "Cilantro",
        "category": "Leafy Greens",
        "sample_price": 0.99,
        "package_size": "bunch",
        "image_url": product_image("cilantro bunch"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Choose bright, fragrant bunches with no slimy stems.",
    },
    {
        "name": "Mint",
        "category": "Leafy Greens",
        "sample_price": 1.99,
        "package_size": "bunch",
        "image_url": product_image("fresh mint bunch"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Avoid blackened leaves and limp stems.",
    },
    {
        "name": "Parsley",
        "category": "Leafy Greens",
        "sample_price": 1.49,
        "package_size": "bunch",
        "image_url": product_image("parsley bunch"),
        "typical_shelf_life_days": 4,
        "max_realistic_shelf_life_days": 8,
        "guidance": "Choose bright bunches with firm stems.",
    },
    {
        "name": "Bread",
        "category": "Bread/Wheat",
        "sample_price": 3.29,
        "package_size": "20 oz loaf",
        "image_url": product_image("sandwich bread loaf"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Check best-by date and avoid crushed loaves.",
    },
    {
        "name": "Whole Wheat Bread",
        "category": "Bread/Wheat",
        "sample_price": 3.79,
        "package_size": "20 oz loaf",
        "image_url": product_image("whole wheat bread"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose the latest best-by date and intact packaging.",
    },
    {
        "name": "Bagels",
        "category": "Bread/Wheat",
        "sample_price": 4.49,
        "package_size": "6 count",
        "image_url": product_image("bagels bakery"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Prefer fresh packs with no moisture inside the bag.",
    },
    {
        "name": "Muffins",
        "category": "Bakery",
        "sample_price": 6.49,
        "package_size": "4 count",
        "image_url": product_image("muffins bakery"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Prefer same-day bakery packs when available.",
    },
    {
        "name": "Croissants",
        "category": "Bakery",
        "sample_price": 5.99,
        "package_size": "6 count",
        "image_url": product_image("croissants bakery"),
        "typical_shelf_life_days": 2,
        "max_realistic_shelf_life_days": 5,
        "guidance": "Choose freshly packed croissants without crushed corners.",
    },
    {
        "name": "Cookies",
        "category": "Bakery",
        "sample_price": 4.99,
        "package_size": "12 count",
        "image_url": product_image("bakery cookies"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 14,
        "guidance": "Select sealed packs with the freshest bakery date.",
    },
    {
        "name": "Bananas",
        "category": "Produce/Fruits",
        "sample_price": 0.69,
        "package_size": "per lb",
        "image_url": product_image("bananas fruit"),
        "typical_shelf_life_days": 4,
        "max_realistic_shelf_life_days": 8,
        "guidance": "Match ripeness preference: green, slightly green, or yellow.",
    },
    {
        "name": "Avocados",
        "category": "Produce/Fruits",
        "sample_price": 1.49,
        "package_size": "each",
        "image_url": product_image("avocados fruit"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Match firmness preference: firm, medium, or ripe.",
    },
    {
        "name": "Apples",
        "category": "Produce/Fruits",
        "sample_price": 1.99,
        "package_size": "per lb",
        "image_url": product_image("apples fruit"),
        "typical_shelf_life_days": 14,
        "max_realistic_shelf_life_days": 30,
        "guidance": "Choose firm apples without bruises.",
    },
    {
        "name": "Oranges",
        "category": "Produce/Fruits",
        "sample_price": 1.79,
        "package_size": "per lb",
        "image_url": product_image("oranges fruit"),
        "typical_shelf_life_days": 10,
        "max_realistic_shelf_life_days": 21,
        "guidance": "Pick heavy, firm oranges without soft spots.",
    },
    {
        "name": "Strawberries",
        "category": "Produce/Fruits",
        "sample_price": 4.49,
        "package_size": "1 lb clamshell",
        "image_url": product_image("strawberries fruit"),
        "typical_shelf_life_days": 3,
        "max_realistic_shelf_life_days": 7,
        "guidance": "Avoid mold, leaking berries, or excess moisture.",
    },
    {
        "name": "Blueberries",
        "category": "Produce/Fruits",
        "sample_price": 4.99,
        "package_size": "pint",
        "image_url": product_image("blueberries fruit"),
        "typical_shelf_life_days": 5,
        "max_realistic_shelf_life_days": 10,
        "guidance": "Choose firm berries with no crushed or moldy fruit.",
    },
]

PREFERENCES = [
    {
        "customer_id": 1,
        "category": "Dairy",
        "product_name": "Whole Milk",
        "min_shelf_life_days": 10,
        "ripeness": None,
        "substitution_preference": "Ask before replacing",
        "notes": "Use for weekday breakfasts.",
        "save_as_default": 1,
    },
    {
        "customer_id": 1,
        "category": "Produce/Fruits",
        "product_name": "Bananas",
        "min_shelf_life_days": None,
        "ripeness": "slightly green",
        "substitution_preference": "Do not replace",
        "notes": "Avoid fully yellow bananas unless there is no alternative.",
        "save_as_default": 1,
    },
    {
        "customer_id": 1,
        "category": "Meat",
        "product_name": "Chicken Breast",
        "min_shelf_life_days": 4,
        "ripeness": None,
        "substitution_preference": "Allow replacement",
        "notes": "Freeze-ready family pack is okay.",
        "save_as_default": 0,
    },
    {
        "customer_id": 2,
        "category": "Bakery",
        "product_name": "Muffins",
        "min_shelf_life_days": 5,
        "ripeness": None,
        "substitution_preference": "Ask before replacing",
        "notes": "Prefer bakery date from today.",
        "save_as_default": 0,
    },
    {
        "customer_id": 2,
        "category": "Produce/Fruits",
        "product_name": "Avocados",
        "min_shelf_life_days": None,
        "ripeness": "firm",
        "substitution_preference": "Do not replace",
        "notes": "For later in the week.",
        "save_as_default": 1,
    },
]


def seed_database(db: Connection) -> None:
    for customer in CUSTOMERS:
        db.execute(
            """
            INSERT INTO customers (id, name)
            VALUES (?, ?)
            ON CONFLICT(id) DO UPDATE SET name = excluded.name
            """,
            (customer["id"], customer["name"]),
        )

    db.execute(
        """
        UPDATE products
        SET name = 'Whole Milk'
        WHERE name = 'Milk'
          AND NOT EXISTS (SELECT 1 FROM products WHERE name = 'Whole Milk')
        """
    )
    db.execute(
        """
        UPDATE products
        SET name = 'Chicken Breast'
        WHERE name = 'Chicken'
          AND NOT EXISTS (SELECT 1 FROM products WHERE name = 'Chicken Breast')
        """
    )
    db.execute("UPDATE products SET category = 'Produce/Fruits' WHERE category = 'Produce'")
    db.execute("UPDATE preferences SET category = 'Produce/Fruits' WHERE category = 'Produce'")

    for product in PRODUCTS:
        db.execute(
            """
            INSERT INTO products (
                name,
                category,
                sample_price,
                package_size,
                image_url,
                typical_shelf_life_days,
                max_realistic_shelf_life_days,
                guidance
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(name) DO UPDATE SET
                category = excluded.category,
                sample_price = excluded.sample_price,
                package_size = excluded.package_size,
                image_url = excluded.image_url,
                typical_shelf_life_days = excluded.typical_shelf_life_days,
                max_realistic_shelf_life_days = excluded.max_realistic_shelf_life_days,
                guidance = excluded.guidance
            """,
            (
                product["name"],
                product["category"],
                product["sample_price"],
                product["package_size"],
                product["image_url"],
                product["typical_shelf_life_days"],
                product["max_realistic_shelf_life_days"],
                product["guidance"],
            ),
        )

    product_lookup = {
        row["name"]: row["id"] for row in db.execute("SELECT id, name FROM products")
    }
    now = datetime.now(UTC).isoformat()

    if db.execute("SELECT id FROM preferences LIMIT 1").fetchone():
        db.commit()
        return

    for preference_seed in PREFERENCES:
        preference = preference_seed.copy()
        product_name = preference.pop("product_name")
        db.execute(
            """
            INSERT INTO preferences (
                customer_id,
                category,
                product_id,
                min_shelf_life_days,
                ripeness,
                substitution_preference,
                notes,
                save_as_default,
                created_at
            )
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            (
                preference["customer_id"],
                preference["category"],
                product_lookup[product_name],
                preference["min_shelf_life_days"],
                preference["ripeness"],
                preference["substitution_preference"],
                preference["notes"],
                preference["save_as_default"],
                now,
            ),
        )

    db.commit()
